### ISSUE TITLE
Checklist for solve cooldown

### ISSUE THREAD

**Issue by Kirdow** [Kirdow/Kubewatch#1]
There should be a cooldown after a solve to prevent double tap accidents.

- [ ] Cooldown duration should be an option
- [x] There should be an indicator of an active cooldown
  - Currently it's done by making the small timer green while cooldown is active.
  - [ ] Cooldown indicator color should be an option
