### ISSUE TITLE
Checklist for timer history

### ISSUE THREAD

**Issue by Kirdow** [Kirdow/Kubewatch#2]
There should be timer history for past solves, this should include as much data as possible for the solve and scramble.

- Each entry should contain:
  - [x] The scramble sequence used for that solve
  - [x] Data/Time of the solve
  - [x] The time it took for the solve
  - [x] Worst time indicator
  - [x] Worst 10% indicator
  - [x] Best 10% indicator
  - [x] Best time indicator
- Interactions with the history
  - [x] Remove individual solves from the history list
    - [x] Undo deletion of an entry
  - [x] Recall a solve onto the main screen
  - [x] Copy a scramble used for a solve onto clipboard
  - [x] Sort list by solve time
  - [x] Sort list by date time
- Other
  - [x] Persistent storage
    - [x] Support for disk storage
    - [ ] Support for cloud storage on supported platforms

**Comment by Kirdow** [comment]
Everything is implemented except for cloud storage as of 1ff6e93. Added a few points as well like worst/best indicators and list sorting.
