### ISSUE TITLE
Checklist for inspection time

### ISSUE THREAD

**Issue by Kirdow** [Kirdow/Kubewatch#5]
There should be an option for inspection time. This would play a sound after the inspection time expires. This should have options for both indication type as well as time limit. No limit means no inspection time.

- Indicators
  - [ ] Play a beep sound when inspection time ends
  - [ ] Hide the cube when inspection time ends?
  - [ ] Auto start timer when inspection time ends
- Timing
  - [x] No inspection time
  - [ ] 3 seconds
  - [ ] 5 seconds
  - [ ] 8 seconds
  - [ ] 10 seconds
  - [ ] 15 seconds
